### ISSUE TITLE
Emacs GUI doesn’t run on elementary OS

### ISSUE THREAD

**Issue by kenokenobingo** [elementary/tasks#118] opened 2020-05-13 16:18 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When I try to open Emacs GUI in elementary OS, it fails.

### To Reproduce
1. Install Emacs with `apt install emacs`
2. Try to open Emacs either with the terminal or the elementary OS menu

### Expected behavior
Emacs should be running properly.

### Logs

Terminal output:

```
X protocol error: BadMatch (invalid parameter attributes) on protocol request 139
When compiled with GTK, Emacs cannot recover from X disconnects.
This is a GTK bug: https://bugzilla.gnome.org/show_bug.cgi?id=85715
For details, see etc/PROBLEMS.
Fatal error 6: Aborted
Backtrace:
emacs[0x50a4de]
emacs[0x4f0ad9]
emacs[0x50a583]
emacs[0x4c0920]
emacs[0x4c4c69]
emacs[0x4c4ceb]
/usr/lib/x86_64-linux-gnu/libX11.so.6(_XError+0x11a)[0x7fdf5a18b8fa]
/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x3d82b)[0x7fdf5a18882b]
/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x3d8d5)[0x7fdf5a1888d5]
/usr/lib/x86_64-linux-gnu/libX11.so.6(_XEventsQueued+0x55)[0x7fdf5a189205]
/usr/lib/x86_64-linux-gnu/libX11.so.6(XPending+0x5d)[0x7fdf5a17ad3d]
/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x6809e)[0x7fdf5b9a609e]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_prepare+0x1c8)[0x7fdf5a8f1b28]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c4fb)[0x7fdf5a8f24fb]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_pending+0x27)[0x7fdf5a8f2687]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_events_pending+0xd)[0x7fdf5be63a9d]
emacs[0x4c1327]
emacs[0x4f7a01]
emacs[0x4f8095]
emacs[0x5b2740]
emacs[0x5b3d48]
emacs[0x5b40d4]
emacs[0x49299a]
emacs[0x499ce5]
emacs[0x5231b3]
emacs[0x563b59]
emacs[0x598413]
emacs[0x565ead]
emacs[0x5639fb]
emacs[0x5669d9]
emacs[0x588cd1]
emacs[0x563b59]
emacs[0x598413]
emacs[0x565ead]
emacs[0x5639fb]
emacs[0x563cfa]
emacs[0x56cf0c]
emacs[0x56d36f]
emacs[0x563b92]
emacs[0x598413]
emacs[0x565ead]
...
Aborted
```
The mentioned issue is tagged as resolved in the GNOME tracker.

## Platform Information

![About screen](https://user-images.githubusercontent.com/9639767/81838107-f988de00-9545-11ea-93b4-cd6405fded4d.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by cassidyjames** [comment] 2020-05-13 18:44
Duplicate of https://github.com/elementary/tasks/issues/118

**Closed by cassidyjames** 2020-05-13 18:44 UTC
